### ISSUE TITLE
Duplicated gates should compile to different names

### ISSUE THREAD

**Issue by ysiraichi** [ysiraichi/enfield#2]
Since we, by default, include the library `qelib1.inc`, we can't just issue an error for that. There are two options:

- Just get the last gate definition (bad because it issues an error at `qiskit` compiler);
- Rename the same name gate definitions (way to go).

So:
```
gate id a { }
gate id a { }
id q[0];
```

would turn into:
```
gate id a { }
gate id_1 a { }
id_1 q[0];
```

Thus, we would always use the last definition while being compatible with `qiskit` compiler.

**Comment by LionsWrath** [comment]
Isso considera sempre que as duas definições são iguais né? Pode ocorrer delas fazerem coisas diferentes e por exemplo a última ser sempre considerada?

**Comment by ysiraichi** [comment]
Nope. They may be different. That's why we should just use the last one.

**Comment by LionsWrath** [comment]
We will still do this one? The QISKitenv is already working, right?

**Comment by ysiraichi** [comment]
It is already working, however we have to find a way to deal with this. I don't know how to deal with this properly, what do you think, @LionsWrath ? If you don't know how to deal with this too, we can just close it for now.
